#ifndef JETSONTK1_MAP_H
#define JETSONTK1_MAP_H 

//Arbitration Semaphore
#define JETSON_ARBI_SEMAPHORE_BASE						0x60002000
#define JETSON_ARBI_SEMAPHORE_SIZE						0x1000

//Flow Controller
#define JETSON_FLOW_CONTROLLER_BASE						0x60007000
#define JETSON_FLOW_CONTROLLER_SIZE						0x1000

//Exception vectors
#define JETSON_EXCEPTION_VECTORS_BASE					0x6000f000
#define JETSON_EXCEPTION_VECTORS_SIZE					0x1000

#define JETSON_PA_RESET_VECTOR							0x6000f500

#define JETSON_APB_MISC_BASE							0x70000000
//jetson tk1 uart
#define	JETSON_APB_UARTA								(JETSON_APB_MISC_BASE + 0x6000)
#define JETSON_APB_UARTA_SIZE							0x40
#define	JETSON_APB_UARTB								(JETSON_APB_MISC_BASE + 0x6040)
#define JETSON_APB_UARTB_SIZE							0x40
#define	JETSON_APB_UARTC								(JETSON_APB_MISC_BASE + 0x6200)
#define JETSON_APB_UARTC_SIZE							0x100
#define	JETSON_APB_UARTD								(JETSON_APB_MISC_BASE + 0x6300)
#define JETSON_APB_UARTD_SIZE							0x100
#define JETSON_APB_UARTD_SIZE_ALLOC						0x1000

// Net(RTL8196) BASE ADDR
// FIXME: should use pci driver.
#define JETSON_PCIE_NETBASE                             0x13000000

// Jetson-tk1 DDR MEM
#define JETSONTK1_DDR_MEM_HIGHADDR						0xFFFFFFFF
#define JETSONTK1_DDR_MEM_BASEADDR						0x80000000

#endif	// JETSONTK1_MAP_H
