
#ifndef _ZYNQMP_MAP_H_
#define _ZYNQMP_MAP_H_

#ifdef __cplusplus
extern "C" {
#endif
/************************** Constant Definitions *****************************/

/*
 * This block contains constant declarations for the peripherals
 * within the hardblock
 */

/* Canonical definitions for PS-DDR MEMORY */
#define ZYNQMP_PSDDR_MEM_BASEADDR		0x00000000U
#define ZYNQMP_PSDDR_MEM_HIGHADDR		0x3FFFFFFFU

/*
 * This block contains constant declarations for the I/O peripherals 
 * attached in 32-bit APB bus within the hardblock. These have been 
 * put for bacwards compatibilty
 * see UG1085, pp:232
 */

#define ZYNQMP_APU_GIC_CPU_BASE        0xF9020000
#define ZYNQMP_APU_GIC_D1ST_BASE       0xF9010000

#define ZYNQMP_PERIPHERAL_BASEADDR         0xFF000000U

#define ZYNQMP_UART0_BASEADDR              0xFF000000U
#define ZYNQMP_UART1_BASEADDR              0xFF010000U
#define ZYNQMP_I2C0_BASEADDR               0xFF020000U
#define ZYNQMP_I2C1_BASEADDR               0xFF030000U
#define ZYNQMP_SPI0_BASEADDR               0xFF040000U
#define ZYNQMP_SPI1_BASEADDR               0xFF050000U
#define ZYNQMP_CAN0_BASEADDR               0xFF060000U
#define ZYNQMP_CAN1_BASEADDR               0xFF070000U
#define ZYNQMP_GPIO_BASEADDR               0xFF0A0000U
#define ZYNQMP_GEM0_BASEADDR               0xFF0B0000U
#define ZYNQMP_GEM1_BASEADDR               0xFF0C0000U
#define ZYNQMP_GEM2_BASEADDR               0xFF0D0000U
#define ZYNQMP_GEM3_BASEADDR               0xFF0E0000U
#define ZYNQMP_QSPI_BASEADDR               0xFF0F0000U
#define ZYNQMP_NAND_BASEADDR               0xFF100000U
#define ZYNQMP_SDIO0_BASEADDR              0xFF160000U
#define ZYNQMP_SDIO1_BASEADDR              0xFF170000U
#define ZYNQMP_IPI_BASEADDR                0xFF990000U
#define ZYNQMP_USB0_BASEADDR               0xFF9D0000U
#define ZYNQMP_USB1_BASEADDR               0xFF9E0000U

/* Sytem monitor register sets */
// todo
#define ZYNQMP_CSU_SWDT_BASEADDR           0xFFCB0000U

/* I/O peripherial register map for FPD */
#define ZYNQMP_SATA_BASEADDR               0xFD0C0000U
#define ZYNQMP_PCIE_BRIEGE_ADDR            0xFD0E0000U
#define ZYNQMP_PCIE_IN_BASEADDR            0xFD0E0800U
#define ZYNQMP_PCIE_EG_BASEADDR            0xFD0E0C00U
#define ZYNQMP_PCIEDMA_BASEADDR            0xFD0F0000U
#define ZYNQMP_SIOU_BASEADDR               0xFD3D0000U
#define ZYNQMP_PSGTR_BASEADDR              0xFD400000U
#define ZYNQMP_PCIE_ATTR_BASEADDR          0xFD480000U
#define ZYNQMP_DP_BASEADDR                 0xFD4A0000U
#define ZYNQMP_GPU_BASEADDR                0xFD4B0000U
#define ZYNQNP_DPDMA_BASEADDR              0xFD4C0000U

/* ps system registers set */
// todo


/* Canonical definitions for Interrupts  */
#define ZYNQMP_XUARTPS_0_INTR		ZYNQMP_UART0_INT_ID
#define ZYNQMP_XUARTPS_1_INTR		ZYNQMP_UART1_INT_ID
#define ZYNQMP_XIICPS_0_INTR		ZYNQMP_I2C0_INT_ID
#define ZYNQMP_XIICPS_1_INTR		ZYNQMP_I2C1_INT_ID
#define ZYNQMP_XSPIPS_0_INTR		ZYNQMP_SPI0_INT_ID
#define ZYNQMP_XSPIPS_1_INTR		ZYNQMP_SPI1_INT_ID
#define ZYNQMP_XCANPS_0_INTR		ZYNQMP_CAN0_INT_ID
#define ZYNQMP_XCANPS_1_INTR		ZYNQMP_CAN1_INT_ID
#define ZYNQMP_XGPIOPS_0_INTR		ZYNQMP_GPIO_INT_ID
#define ZYNQMP_XEMACPS_0_INTR		ZYNQMP_GEM0_INT_ID
#define ZYNQMP_XEMACPS_0_WAKE_INTR	ZYNQMP_GEM0_WAKE_INT_ID
#define ZYNQMP_XEMACPS_1_INTR		ZYNQMP_GEM1_INT_ID
#define ZYNQMP_XEMACPS_1_WAKE_INTR	ZYNQMP_GEM1_WAKE_INT_ID
#define ZYNQMP_XEMACPS_2_INTR		ZYNQMP_GEM2_INT_ID
#define ZYNQMP_XEMACPS_2_WAKE_INTR	ZYNQMP_GEM2_WAKE_INT_ID
#define ZYNQMP_XEMACPS_3_INTR		ZYNQMP_GEM3_INT_ID
#define ZYNQMP_XEMACPS_3_WAKE_INTR	ZYNQMP_GEM3_WAKE_INT_ID
#define ZYNQMP_XSDIOPS_0_INTR		ZYNQMP_SDIO0_INT_ID
#define ZYNQMP_XQSPIPS_0_INTR		ZYNQMP_QSPI_INT_ID
#define ZYNQMP_XSDIOPS_1_INTR		ZYNQMP_SDIO1_INT_ID
#define ZYNQMP_XWDTPS_0_INTR		ZYNQMP_LPD_SWDT_INT_ID
#define ZYNQMP_XWDTPS_1_INTR		ZYNQMP_FPD_SWDT_INT_ID
#define ZYNQMP_XDCFG_0_INTR		ZYNQMP_DVC_INT_ID
#define ZYNQMP_XTTCPS_0_INTR		ZYNQMP_TTC0_0_INT_ID
#define ZYNQMP_XTTCPS_1_INTR		ZYNQMP_TTC0_1_INT_ID
#define ZYNQMP_XTTCPS_2_INTR		ZYNQMP_TTC0_2_INT_ID
#define ZYNQMP_XTTCPS_3_INTR		ZYNQMP_TTC1_0_INT_ID
#define ZYNQMP_XTTCPS_4_INTR		ZYNQMP_TTC1_1_INT_ID
#define ZYNQMP_XTTCPS_5_INTR		ZYNQMP_TTC1_2_INT_ID
#define ZYNQMP_XTTCPS_6_INTR		ZYNQMP_TTC2_0_INT_ID
#define ZYNQMP_XTTCPS_7_INTR		ZYNQMP_TTC2_1_INT_ID
#define ZYNQMP_XTTCPS_8_INTR		ZYNQMP_TTC2_2_INT_ID
#define ZYNQMP_XTTCPS_9_INTR		ZYNQMP_TTC3_0_INT_ID
#define ZYNQMP_XTTCPS_10_INTR		ZYNQMP_TTC3_1_INT_ID
#define ZYNQMP_XTTCPS_11_INTR		ZYNQMP_TTC3_2_INT_ID
#define ZYNQMP_XNANDPS8_0_INTR        	ZYNQMP_NAND_INT_ID
#define ZYNQMP_XADMAPS_0_INTR 		ZYNQMP_ADMA_CH0_INT_ID
#define ZYNQMP_XADMAPS_1_INTR 		ZYNQMP_ADMA_CH1_INT_ID
#define ZYNQMP_XADMAPS_2_INTR		ZYNQMP_ADMA_CH2_INT_ID
#define ZYNQMP_XADMAPS_3_INTR 		ZYNQMP_ADMA_CH3_INT_ID
#define ZYNQMP_XADMAPS_4_INTR		ZYNQMP_ADMA_CH4_INT_ID
#define ZYNQMP_XADMAPS_5_INTR 		ZYNQMP_ADMA_CH5_INT_ID
#define ZYNQMP_XADMAPS_6_INTR 		ZYNQMP_ADMA_CH6_INT_ID
#define ZYNQMP_XADMAPS_7_INTR 		ZYNQMP_ADMA_CH7_INT_ID
#define ZYNQMP_XCSUDMA_INTR 		ZYNQMP_CSU_DMA_INT_ID
#define ZYNQMP_PSU_ADMA_0_INTR 		ZYNQMP_ADMA_CH0_INT_ID
#define ZYNQMP_PSU_ADMA_1_INTR 		ZYNQMP_ADMA_CH1_INT_ID
#define ZYNQMP_PSU_ADMA_2_INTR		ZYNQMP_ADMA_CH2_INT_ID
#define ZYNQMP_PSU_ADMA_3_INTR 		ZYNQMP_ADMA_CH3_INT_ID
#define ZYNQMP_PSU_ADMA_4_INTR		ZYNQMP_ADMA_CH4_INT_ID
#define ZYNQMP_PSU_ADMA_5_INTR 		ZYNQMP_ADMA_CH5_INT_ID
#define ZYNQMP_PSU_ADMA_6_INTR 		ZYNQMP_ADMA_CH6_INT_ID
#define ZYNQMP_PSU_ADMA_7_INTR 		ZYNQMP_ADMA_CH7_INT_ID
#define ZYNQMP_PSU_CSUDMA_INTR 		ZYNQMP_CSU_DMA_INT_ID
#define ZYNQMP_XMPU_LPD_INTR 		ZYNQMP_XMPU_LPD_INT_ID
#define ZYNQMP_XZDMAPS_0_INTR		ZYNQMP_ZDMA_CH0_INT_ID
#define ZYNQMP_XZDMAPS_1_INTR		ZYNQMP_ZDMA_CH1_INT_ID
#define ZYNQMP_XZDMAPS_2_INTR 		ZYNQMP_ZDMA_CH2_INT_ID
#define ZYNQMP_XZDMAPS_3_INTR 		ZYNQMP_ZDMA_CH3_INT_ID
#define ZYNQMP_XZDMAPS_4_INTR		ZYNQMP_ZDMA_CH4_INT_ID
#define ZYNQMP_XZDMAPS_5_INTR 		ZYNQMP_ZDMA_CH5_INT_ID
#define ZYNQMP_XZDMAPS_6_INTR 		ZYNQMP_ZDMA_CH6_INT_ID
#define ZYNQMP_XZDMAPS_7_INTR 		ZYNQMP_ZDMA_CH7_INT_ID
#define ZYNQMP_PSU_GDMA_0_INTR		ZYNQMP_ZDMA_CH0_INT_ID
#define ZYNQMP_PSU_GDMA_1_INTR		ZYNQMP_ZDMA_CH1_INT_ID
#define ZYNQMP_PSU_GDMA_2_INTR 		ZYNQMP_ZDMA_CH2_INT_ID
#define ZYNQMP_PSU_GDMA_3_INTR 		ZYNQMP_ZDMA_CH3_INT_ID
#define ZYNQMP_PSU_GDMA_4_INTR		ZYNQMP_ZDMA_CH4_INT_ID
#define ZYNQMP_PSU_GDMA_5_INTR 		ZYNQMP_ZDMA_CH5_INT_ID
#define ZYNQMP_PSU_GDMA_6_INTR 		ZYNQMP_ZDMA_CH6_INT_ID
#define ZYNQMP_PSU_GDMA_7_INTR 		ZYNQMP_ZDMA_CH7_INT_ID
#define ZYNQMP_XMPU_FPD_INTR 		ZYNQMP_XMPU_FPD_INT_ID
#define ZYNQMP_XCCI_FPD_INTR 		ZYNQMP_FPD_CCI_INT_ID
#define ZYNQMP_XSMMU_FPD_INTR 		ZYNQMP_FPD_SMMU_INT_ID
#define ZYNQMP_XUSBPS_0_INTR		ZYNQMP_USB3_0_ENDPT_INT_ID
#define ZYNQMP_XUSBPS_1_INTR		ZYNQMP_USB3_1_ENDPT_INT_ID
#define ZYNQMP_XUSBPS_0_WAKE_INTR		ZYNQMP_USB3_0_WAKE_INT_ID
#define ZYNQMP_XUSBPS_1_WAKE_INTR		ZYNQMP_USB3_1_WAKE_INT_ID
#define	ZYNQMP_XRTCPSU_ALARM_INTR 	ZYNQMP_RTC_ALARM_INT_ID
#define	ZYNQMP_XRTCPSU_SECONDS_INTR	ZYNQMP_RTC_SEC_INT_ID
#define ZYNQMP_XAPMPS_0_INTR		ZYNQMP_APM0_INT_ID
#define ZYNQMP_XAPMPS_1_INTR		ZYNQMP_APM1_INT_ID
#define ZYNQMP_XAPMPS_2_INTR		ZYNQMP_APM2_INT_ID
#define ZYNQMP_XAPMPS_5_INTR		ZYNQMP_APM5_INT_ID
#define ZYNQMP_XSYSMONPSU_INTR		ZYNQMP_AMS_INT_ID

/* Canonical definitions for SCU GIC */
#define ZYNQMP_SCUGIC_NUM_INSTANCES	1U
#define ZYNQMP_SCUGIC_SINGLE_DEVICE_ID	0U
#define ZYNQMP_SCUGIC_CPU_BASEADDR	(ZYNQMP_SCU_PERIPH_BASE + 0x00001000U)
#define ZYNQMP_SCUGIC_DIST_BASEADDR	(ZYNQMP_SCU_PERIPH_BASE + 0x00002000U)
#define ZYNQMP_SCUGIC_ACK_BEFORE		0U

#define ZYNQMP_CPU_CORTEXA53_CORE_CLOCK_FREQ_HZ	ZYNQMP_CPU_CORTEXA53_0_CPU_CLK_FREQ_HZ


/*
 * This block contains constant declarations for the peripherals
 * within the hardblock. These have been put for backwards compatibilty
 */


#define ZYNQMP_SYS_CTRL_BASEADDR	0xFF180000U
#define ZYNQMP_SCU_PERIPH_BASE		0xF9000000U



/* Shared Peripheral Interrupts (SPI) */
#define ZYNQMP_FPGA0_INT_ID		121U
#define ZYNQMP_FPGA1_INT_ID		122U
#define ZYNQMP_FPGA2_INT_ID		123U
#define ZYNQMP_FPGA3_INT_ID		124U
#define ZYNQMP_FPGA4_INT_ID		125U
#define ZYNQMP_FPGA5_INT_ID		126U
#define ZYNQMP_FPGA6_INT_ID		127U
#define ZYNQMP_FPGA7_INT_ID		128U
#define ZYNQMP_FPGA8_INT_ID		136U
#define ZYNQMP_FPGA9_INT_ID		137U
#define ZYNQMP_FPGA10_INT_ID		138U
#define ZYNQMP_FPGA11_INT_ID		139U
#define ZYNQMP_FPGA12_INT_ID		140U
#define ZYNQMP_FPGA13_INT_ID		141U
#define ZYNQMP_FPGA14_INT_ID		142U
#define ZYNQMP_FPGA15_INT_ID		143U

/* Updated Interrupt-IDs */
#define ZYNQMP_OCMINTR_INT_ID		(10U + 32U)
#define ZYNQMP_NAND_INT_ID        		(14U + 32U)
#define ZYNQMP_QSPI_INT_ID			(15U + 32U)
#define ZYNQMP_GPIO_INT_ID			(16U + 32U)
#define ZYNQMP_I2C0_INT_ID			(17U + 32U)
#define ZYNQMP_I2C1_INT_ID			(18U + 32U)
#define ZYNQMP_SPI0_INT_ID			(19U + 32U)
#define ZYNQMP_SPI1_INT_ID			(20U + 32U)
#define ZYNQMP_UART0_INT_ID		(21U + 32U)
#define ZYNQMP_UART1_INT_ID		(22U + 32U)
#define ZYNQMP_CAN0_INT_ID			(23U + 32U)
#define ZYNQMP_CAN1_INT_ID			(24U + 32U)
#define	ZYNQMP_RTC_ALARM_INT_ID 	(26U + 32U)
#define	ZYNQMP_RTC_SEC_INT_ID	 	(27U + 32U)
#define ZYNQMP_LPD_SWDT_INT_ID		(52U + 32U)
#define ZYNQMP_FPD_SWDT_INT_ID		(113U + 32U)
#define ZYNQMP_TTC0_0_INT_ID		(36U + 32U)
#define ZYNQMP_TTC0_1_INT_ID		(37U + 32U)
#define ZYNQMP_TTC0_2_INT_ID 		(38U + 32U)
#define ZYNQMP_TTC1_0_INT_ID		(39U + 32U)
#define ZYNQMP_TTC1_1_INT_ID		(40U + 32U)
#define ZYNQMP_TTC1_2_INT_ID		(41U + 32U)
#define ZYNQMP_TTC2_0_INT_ID		(42U + 32U)
#define ZYNQMP_TTC2_1_INT_ID		(43U + 32U)
#define ZYNQMP_TTC2_2_INT_ID		(44U + 32U)
#define ZYNQMP_TTC3_0_INT_ID		(45U + 32U)
#define ZYNQMP_TTC3_1_INT_ID		(46U + 32U)
#define ZYNQMP_TTC3_2_INT_ID		(47U + 32U)
#define ZYNQMP_SDIO0_INT_ID		(48U + 32U)
#define ZYNQMP_SDIO1_INT_ID		(49U + 32U)
#define ZYNQMP_AMS_INT_ID			(56U + 32U)
#define ZYNQMP_GEM0_INT_ID			(57U + 32U)
#define ZYNQMP_GEM0_WAKE_INT_ID		(58U + 32U)
#define ZYNQMP_GEM1_INT_ID			(59U + 32U)
#define ZYNQMP_GEM1_WAKE_INT_ID		(60U + 32U)
#define ZYNQMP_GEM2_INT_ID			(61U + 32U)
#define ZYNQMP_GEM2_WAKE_INT_ID		(62U + 32U)
#define ZYNQMP_GEM3_INT_ID			(63U + 32U)
#define ZYNQMP_GEM3_WAKE_INT_ID		(64U + 32U)
#define ZYNQMP_USB3_0_ENDPT_INT_ID		(65U + 32U)
#define ZYNQMP_USB3_1_ENDPT_INT_ID		(70U + 32U)
#define ZYNQMP_USB3_0_WAKE_INT_ID		(75U + 32U)
#define ZYNQMP_USB3_1_WAKE_INT_ID		(76U + 32U)
#define ZYNQMP_ADMA_CH0_INT_ID		(77U + 32U)
#define ZYNQMP_ADMA_CH1_INT_ID		(78U + 32U)
#define ZYNQMP_ADMA_CH2_INT_ID		(79U + 32U)
#define ZYNQMP_ADMA_CH3_INT_ID		(80U + 32U)
#define ZYNQMP_ADMA_CH4_INT_ID		(81U + 32U)
#define ZYNQMP_ADMA_CH5_INT_ID		(82U + 32U)
#define ZYNQMP_ADMA_CH6_INT_ID		(83U + 32U)
#define ZYNQMP_ADMA_CH7_INT_ID		(84U + 32U)
#define ZYNQMP_CSU_DMA_INT_ID		(86U + 32U)
#define ZYNQMP_XMPU_LPD_INT_ID		(88U + 32U)
#define ZYNQMP_ZDMA_CH0_INT_ID		(124U + 32U)
#define ZYNQMP_ZDMA_CH1_INT_ID		(125U + 32U)
#define ZYNQMP_ZDMA_CH2_INT_ID		(126U + 32U)
#define ZYNQMP_ZDMA_CH3_INT_ID		(127U + 32U)
#define ZYNQMP_ZDMA_CH4_INT_ID		(128U + 32U)
#define ZYNQMP_ZDMA_CH5_INT_ID		(129U + 32U)
#define ZYNQMP_ZDMA_CH6_INT_ID		(130U + 32U)
#define ZYNQMP_ZDMA_CH7_INT_ID		(131U + 32U)
#define ZYNQMP_XMPU_FPD_INT_ID		(134U + 32U)
#define ZYNQMP_FPD_CCI_INT_ID		(154U + 32U)
#define ZYNQMP_FPD_SMMU_INT_ID		(155U + 32U)
#define ZYNQMP_APM0_INT_ID		(123U + 32U)
#define ZYNQMP_APM1_INT_ID		(25U + 32U)
#define ZYNQMP_APM2_INT_ID		(25U + 32U)
#define ZYNQMP_APM5_INT_ID		(123U + 32U)

/* REDEFINES for TEST APP */
#define ZYNQMP_PSU_UART_0_INTR        ZYNQMP_UART0_INT_ID
#define ZYNQMP_PSU_UART_1_INTR        ZYNQMP_UART1_INT_ID
#define ZYNQMP_PSU_USB_0_INTR     ZYNQMP_USB0_INT_ID
#define ZYNQMP_PSU_USB_1_INTR     ZYNQMP_USB1_INT_ID
#define ZYNQMP_PSU_I2C_0_INTR     ZYNQMP_I2C0_INT_ID
#define ZYNQMP_PSU_I2C_1_INTR     ZYNQMP_I2C1_INT_ID
#define ZYNQMP_PSU_SPI_0_INTR     ZYNQMP_SPI0_INT_ID
#define ZYNQMP_PSU_SPI_1_INTR     ZYNQMP_SPI1_INT_ID
#define ZYNQMP_PSU_CAN_0_INTR     ZYNQMP_CAN0_INT_ID
#define ZYNQMP_PSU_CAN_1_INTR     ZYNQMP_CAN1_INT_ID
#define ZYNQMP_PSU_GPIO_0_INTR        ZYNQMP_GPIO_INT_ID
#define ZYNQMP_PSU_ETHERNET_0_INTR    ZYNQMP_GEM0_INT_ID
#define ZYNQMP_PSU_ETHERNET_0_WAKE_INTR   ZYNQMP_GEM0_WAKE_INT_ID
#define ZYNQMP_PSU_ETHERNET_1_INTR    ZYNQMP_GEM1_INT_ID
#define ZYNQMP_PSU_ETHERNET_1_WAKE_INTR   ZYNQMP_GEM1_WAKE_INT_ID
#define ZYNQMP_PSU_ETHERNET_2_INTR    ZYNQMP_GEM2_INT_ID
#define ZYNQMP_PSU_ETHERNET_2_WAKE_INTR   ZYNQMP_GEM2_WAKE_INT_ID
#define ZYNQMP_PSU_ETHERNET_3_INTR    ZYNQMP_GEM3_INT_ID
#define ZYNQMP_PSU_ETHERNET_3_WAKE_INTR   ZYNQMP_GEM3_WAKE_INT_ID
#define ZYNQMP_PSU_QSPI_0_INTR        ZYNQMP_QSPI_INT_ID
#define ZYNQMP_PSU_WDT_0_INTR    		ZYNQMP_LPD_SWDT_INT_ID
#define ZYNQMP_PSU_WDT_1_INTR     	ZYNQMP_FPD_SWDT_INT_ID
#define ZYNQMP_PSU_XADC_0_INTR        ZYNQMP_SYSMON_INT_ID
#define ZYNQMP_PSU_TTC_0_INTR         ZYNQMP_TTC0_0_INT_ID
#define ZYNQMP_PSU_TTC_1_INTR         ZYNQMP_TTC0_1_INT_ID
#define ZYNQMP_PSU_TTC_2_INTR         ZYNQMP_TTC0_2_INT_ID
#define ZYNQMP_PSU_TTC_3_INTR         ZYNQMP_TTC1_0_INT_ID
#define ZYNQMP_PSU_TTC_4_INTR         ZYNQMP_TTC1_1_INT_ID
#define ZYNQMP_PSU_TTC_5_INTR         ZYNQMP_TTC1_2_INT_ID
#define ZYNQMP_PSU_TTC_6_INTR			ZYNQMP_TTC2_0_INT_ID
#define ZYNQMP_PSU_TTC_7_INTR			ZYNQMP_TTC2_1_INT_ID
#define ZYNQMP_PSU_TTC_8_INTR			ZYNQMP_TTC2_2_INT_ID
#define ZYNQMP_PSU_TTC_9_INTR			ZYNQMP_TTC3_0_INT_ID
#define ZYNQMP_PSU_TTC_10_INTR		ZYNQMP_TTC3_1_INT_ID
#define ZYNQMP_PSU_TTC_11_INTR		ZYNQMP_TTC3_2_INT_ID
#define ZYNQMP_PSU_AMS_INTR			ZYNQMP_AMS_INT_ID

#define ZYNQMP_XADCPS_NUM_INSTANCES 1U
#define ZYNQMP_XADCPS_0_DEVICE_ID   0U
#define ZYNQMP_XADCPS_0_BASEADDR	  (0xF8007000U)
#define ZYNQMP_XADCPS_INT_ID		ZYNQMP_SYSMON_INT_ID

/* For backwards compatibilty */
#define ZYNQMP_XUARTPS_0_CLOCK_HZ		ZYNQMP_XUARTPS_0_UART_CLK_FREQ_HZ
#define ZYNQMP_XUARTPS_1_CLOCK_HZ		ZYNQMP_XUARTPS_1_UART_CLK_FREQ_HZ
#define ZYNQMP_XTTCPS_0_CLOCK_HZ		ZYNQMP_XTTCPS_0_TTC_CLK_FREQ_HZ
#define ZYNQMP_XTTCPS_1_CLOCK_HZ		ZYNQMP_XTTCPS_1_TTC_CLK_FREQ_HZ
#define ZYNQMP_XTTCPS_2_CLOCK_HZ		ZYNQMP_XTTCPS_2_TTC_CLK_FREQ_HZ
#define ZYNQMP_XTTCPS_3_CLOCK_HZ		ZYNQMP_XTTCPS_3_TTC_CLK_FREQ_HZ
#define ZYNQMP_XTTCPS_4_CLOCK_HZ		ZYNQMP_XTTCPS_4_TTC_CLK_FREQ_HZ
#define ZYNQMP_XTTCPS_5_CLOCK_HZ		ZYNQMP_XTTCPS_5_TTC_CLK_FREQ_HZ
#define ZYNQMP_XIICPS_0_CLOCK_HZ		ZYNQMP_XIICPS_0_I2C_CLK_FREQ_HZ
#define ZYNQMP_XIICPS_1_CLOCK_HZ		ZYNQMP_XIICPS_1_I2C_CLK_FREQ_HZ

#define ZYNQMP_XQSPIPS_0_CLOCK_HZ		ZYNQMP_XQSPIPS_0_QSPI_CLK_FREQ_HZ

#ifdef ZYNQMP_CPU_CORTEXA53_0_CPU_CLK_FREQ_HZ
#define ZYNQMP_CPU_CORTEXA53_CORE_CLOCK_FREQ_HZ	ZYNQMP_CPU_CORTEXA53_0_CPU_CLK_FREQ_HZ
#endif

#ifdef ZYNQMP_CPU_CORTEXA53_1_CPU_CLK_FREQ_HZ
#define ZYNQMP_CPU_CORTEXA53_CORE_CLOCK_FREQ_HZ	ZYNQMP_CPU_CORTEXA53_1_CPU_CLK_FREQ_HZ
#endif

#define ZYNQMP_SCUWDT_DEVICE_ID		0U

#ifdef __cplusplus
}
#endif

#endif /* _ZYNQMP_MAP_H_ */